/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author MoaathAlrajab
 */
public class Homework09 {
    public static void main(String[] args) {
        int targetDivisors = 100;
        int triangleNumber = 1;
        int naturalNumber = 2;

        while (true) {
            // The method to calculate the natural number
            triangleNumber += naturalNumber;
            // Incrementing the natural number
            naturalNumber++;

            // Initializing divisors counter
            int divisorCount = countDivisors(triangleNumber);

            // Checking if the current triangle number have over the divisors number
            if (divisorCount > targetDivisors) {
                System.out.println("The first triangle number to have over " + targetDivisors + " divisors is: " + triangleNumber);
                break;
            }
        }
    }

    // The function to count the divisor number
    public static int countDivisors(int n) {
        int count = 0;
        for (int i = 1; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                if (n / i == i) {
                    count++;
                } else {
                    count += 2;
                }
            }
        }
        return count;
    }
}

// ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?

Answer: the first triangle number is 73920

    */
